server:
  port: 8899
  contextPath : /kafka
spring:
  application:
    name: kafka
  kafka:
    bootstrapServers: 10.90.7.2:9092,10.90.2.101:9092,10.90.2.102:9092
    consumer:
      groupId: kefu-logger
      enable-auto-commit: false
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      groupId: kefu-logger
      retries: 3
      buffer-memory: 20480
      keyDeserializer: org.apache.kafka.common.serialization.StringSerializer
      valueDserializer: org.apache.kafka.common.serialization.StringSerializer
    #listener:
    #  ack-mode: MANUAL_IMMEDIATE